version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ccoa_backend
    ports:
      - "8000:8000"
    volumes:
      - ./docker-data/chroma:/app/chroma_db
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: ccoa_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  chroma_data:
    driver: local